/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package algoritmos;

import Demo.Menu;

/**
 *
 * @author Marko
 */
public class GraficoConjunto extends javax.swing.JFrame {
    
    ClaseConjunto Muestra=new ClaseConjunto();
    int Contador=1;

    public GraficoConjunto() {
        initComponents();
        this.setLocationRelativeTo(null);
        btntranparente();
    }
    
    public void btntranparente(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCr = new javax.swing.JTextField();
        txtCb = new javax.swing.JTextField();
        btnNDatosA = new javax.swing.JButton();
        btnDatosA = new javax.swing.JButton();
        btnDatosB = new javax.swing.JButton();
        btnNDatosB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimetrica = new javax.swing.JButton();
        btnDiferencia = new javax.swing.JButton();
        btnInterseccion = new javax.swing.JButton();
        btnUnion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCa = new javax.swing.JTextField();
        lblRes = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 300, 20));

        txtCb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 20));

        btnNDatosA.setText("N° Datos A");
        btnNDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNDatosAActionPerformed(evt);
            }
        });
        getContentPane().add(btnNDatosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        btnDatosA.setText("Dato:");
        btnDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, -1));

        btnDatosB.setText("Dato:");
        btnDatosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosBActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, -1));

        btnNDatosB.setText("N° Datos B");
        btnNDatosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNDatosBActionPerformed(evt);
            }
        });
        getContentPane().add(btnNDatosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel3.setText("Operaciones de Conjuntos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Alamacenamiento de datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        btnSimetrica.setText("Dif. Simétrica");
        btnSimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimetricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimetrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, -1));

        btnDiferencia.setText("Diferencia");
        btnDiferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, -1));

        btnInterseccion.setText("Intersección");
        btnInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterseccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        btnUnion.setText("Unión");
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Operaciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtCa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 20));

        lblRes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblRes.setText("RESULTADO");
        getContentPane().add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 100, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel1.setText("Conjunto B");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setText("Guardar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("Guardar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel2.setText("Conjunto A");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wer.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 480, 250));

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNDatosAActionPerformed
        // TODO add your handling code here:
        Muestra.ConjuntoCa(Integer.parseInt(txtCa.getText()));
        btnDatosA.setText("Dato: 1/"+Muestra.LongA());
        txtCa.setText(null);
        txtCa.requestFocus();
        btnNDatosA.setEnabled(false);
    }//GEN-LAST:event_btnNDatosAActionPerformed

    private void btnNDatosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNDatosBActionPerformed
        // TODO add your handling code here:
        Muestra.ConjuntoCb(Integer.parseInt(txtCb.getText()));
        btnDatosB.setText("Dato: 1 /"+Muestra.LongB());
        txtCb.setText(null);
        txtCb.requestFocus();
        btnNDatosB.setEnabled(false);
    }//GEN-LAST:event_btnNDatosBActionPerformed

    private void btnDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAActionPerformed
        // TODO add your handling code here:
        Muestra.Ca(txtCa.getText(),Contador-1);
        txtCa.setText(null);
        txtCa.requestFocus();
        Contador++;

        if (Contador>Muestra.LongA()){
            for(int i=1;i<=Muestra.LongA();i++){
                txtCa.setText(txtCa.getText()+Muestra.Ca(i-1)+";");
            }
            txtCa.setText("{"+txtCa.getText()+"}");
            Contador=1;
            btnDatosA.setEnabled(false);
        }
        else{
            btnDatosA.setText("Dato: "+Contador+" / "+Muestra.LongA());
            }
                       
    }//GEN-LAST:event_btnDatosAActionPerformed

    private void btnDatosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosBActionPerformed
        // TODO add your handling code here:
        Muestra.Cb(txtCb.getText(),Contador-1);
        txtCb.setText(null);
        txtCb.requestFocus();
        Contador++;

        if (Contador>Muestra.LongB()){
            for(int i=1;i<=Muestra.LongB();i++){
                txtCb.setText(txtCb.getText()+Muestra.Cb(i-1)+";");
            }
            txtCb.setText("{"+txtCb.getText()+"}");
            Contador=1;
            btnDatosB.setEnabled(false);
        }
        else{
            btnDatosB.setText("Dato: "+Contador+" / "+Muestra.LongB());

        }                           
    }//GEN-LAST:event_btnDatosBActionPerformed

    private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Union()+"}"); 
        lblRes.setText("R = A"+ " U " +"B");
    }//GEN-LAST:event_btnUnionActionPerformed

    private void btnInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterseccionActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Interseccion()+"}"); 
        lblRes.setText("R = A"+ " ∩ "+ "B");
    }//GEN-LAST:event_btnInterseccionActionPerformed

    private void btnDiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiferenciaActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Diferencia()+"}"); 
        lblRes.setText("R = A − B");
    }//GEN-LAST:event_btnDiferenciaActionPerformed

    private void btnSimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimetricaActionPerformed
        // TODO add your handling code here:´´
        txtCr.setText("{" +Muestra.DiferenciaSimetrica()+"}"); 
        lblRes.setText("R = A ∆ B");
    }//GEN-LAST:event_btnSimetricaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        btnNDatosA.setEnabled(true);
        btnNDatosB.setEnabled(true);
        btnDatosA.setEnabled(true);
        btnDatosB.setEnabled(true);
        txtCa.setText("0");
        txtCb.setText("0");
        txtCr.setText("0");
        lblRes.setText("Operacion:");
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDatosA;
    private javax.swing.JButton btnDatosB;
    private javax.swing.JButton btnDiferencia;
    private javax.swing.JButton btnInterseccion;
    private javax.swing.JButton btnNDatosA;
    private javax.swing.JButton btnNDatosB;
    private javax.swing.JButton btnSimetrica;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRes;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtCb;
    private javax.swing.JTextField txtCr;
    // End of variables declaration//GEN-END:variables
}
