/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Demo;
import ListaSimple.ListaS;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Marko
 */
public class JListaSimple extends javax.swing.JFrame {

    /**
     * Creates new form JListaSimple
     */
    public JListaSimple() {
        initComponents();
        this.setLocationRelativeTo(null);
        /*ImageIcon imagen = new ImageIcon("src/Imagenes/Image1.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), java.awt.Image.SCALE_DEFAULT));
        Fondo.setIcon(icono);
        this.repaint();*/
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoMB.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInsertarI = new javax.swing.JButton();
        btnInsertarF = new javax.swing.JButton();
        btnEliminarI = new javax.swing.JButton();
        btnEliminarF = new javax.swing.JButton();
        btnInsertarD = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("LISTA SIMPLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, -1, -1));

        btnInsertarI.setText("Insertar Inicio");
        btnInsertarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarIActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 131, -1));

        btnInsertarF.setText("Insertar Final");
        btnInsertarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 131, -1));

        btnEliminarI.setText("Eliminar Inicio");
        btnEliminarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 131, -1));

        btnEliminarF.setText("Eliminar Final");
        btnEliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 131, -1));

        btnInsertarD.setText("Insertar Despues De");
        btnInsertarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        btnEstado.setText("Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 131, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 55, 219, 222));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 131, -1));

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Image1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 440, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ListaS a;
    private void btnInsertarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarIActionPerformed
        // TODO add your handling code here:
        
        a.insertarP(Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese elemento")));
        jTextArea1.setText("Lista: \n"+a.toString());
        
        
    }//GEN-LAST:event_btnInsertarIActionPerformed

    private void btnInsertarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFActionPerformed
        // TODO add your handling code here:
        
        a.insertarF(Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese elemento")));
        jTextArea1.setText("Lista: \n"+a.toString());
        
    }//GEN-LAST:event_btnInsertarFActionPerformed

    private void btnInsertarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDActionPerformed
        // TODO add your handling code here:
        
        a.insertarD(Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese elemento")),Integer.parseInt(JOptionPane.showInputDialog(null,"Elemento al que reemplazara:")));
        jTextArea1.setText("Lista: \n"+a.toString());
    }//GEN-LAST:event_btnInsertarDActionPerformed

    private void btnEliminarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIActionPerformed
        // TODO add your handling code here:
        
        try{  
            a.eliminar();            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Pila Vacia");    
        }       
        jTextArea1.setText("Pila: \n"+a.toString());
        
    }//GEN-LAST:event_btnEliminarIActionPerformed

    private void btnEliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFActionPerformed
        // TODO add your handling code here:
        
        try{  
            a.eliminarF();            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Pila Vacia");    
        }       
        jTextArea1.setText("Pila: \n"+a.toString());
    }//GEN-LAST:event_btnEliminarFActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        if(a.isEmpty(a))
            jTextArea1.setText("La Lista esta Vacia");
        else
            jTextArea1.setText("La Lista no esta Vacia");
        
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        a = new ListaS();
        JOptionPane.showMessageDialog(null, "Lista Creada");
        jTextArea1.setText("==Ingrese Elementos de la Lista==");
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JListaSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JListaSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JListaSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JListaSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JListaSimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarF;
    private javax.swing.JButton btnEliminarI;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnInsertarD;
    private javax.swing.JButton btnInsertarF;
    private javax.swing.JButton btnInsertarI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
